spring.application.name=municipal
spring.datasource.url=jdbc:mysql://localhost:3306/municipal
spring.datasource.username=root
spring.datasource.password=Dinesh@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
